package com.nokia.parsing.parsers

import ParseAliceFixedNetwork._
import ParseAliceFlexiBSC._
import ParseAliceFlexiMRBTSLTE._
import ParseAliceFlexiMRWCDMABTS._
import ParseAliceLTEOMS._
import ParseAliceSRANBTS._
import ParseAliceWCDMARNC._
import ParseAlicebsc3i._
import ParseAlicemcBSC._
import ParserAlicemcRNC._

object ChooseParser {

  def chooseParser(logElement:String, logFileContent: String):List[Map[String, String]]={

    var parserFunctionReturn = List[Map[String, String]]()
    logElement match {
      case "flexi_bsc__boot_info__zwdi_bootimage" =>
        parserFunctionReturn = flexi_bsc__boot_info__zwdi_bootimage(logFileContent)
      case "flexi_bsc__bts_sw_lmu_and_abis_pool_data__zewl_bts_sw_pack" | "flexi_bsc__bts_sw_lmu_and_abis_pool_data_txt__cellularrnzewl" =>
        parserFunctionReturn = flexi_bsc__bts_sw_lmu_and_abis_pool_data__zewl_bts_sw_pack(logFileContent)
      case "flexi_bsc__bsc_alarm_parameters__zabo_bsc_blk_alarm" =>
        parserFunctionReturn = flexi_bsc__bsc_alarm_parameters__zabo_bsc_blk_alarm(logFileContent)
      case "flexi_bsc__switch_info__training_switch_info" =>
        parserFunctionReturn = flexi_bsc__switch_info__training_switch_info(logFileContent)
      case "flexi_bsc__unit_information__zudh_diagnosis_history" =>
        parserFunctionReturn = flexi_bsc__unit_information__zudh_diagnosis_history(logFileContent)
      case "flexi_bsc__bsc_alarm__zahp_zaho_bsc_alarms" | "mcbsc__bsc__bsc_alarms__zahp_zaho_bsc_alarms" |
           "mcbsc__bsc_alarm__zahp_zaho_bsc_alarms" | "flexi_bsc__bsc_alarm_history_txt__alarm_sup_te" | "bsc3i__bsc_alarms__zahp_zaho_bsc_alarms" =>
        parserFunctionReturn = flexi_bsc__bsc_alarm__zahp_zaho_bsc_alarms(logFileContent)
      case "flexi_bsc__bts_alarm_history__zeoh_bts_alarm_history" | "flexi_bsc__bts_alarm_history__zeoh_bts__alarm_history" | "msbsc__bsc_alarm_history__bsc_alarm" | "flexi_bsc__bts_alarm_history_txt__zeoh_bts" =>
        parserFunctionReturn = flexi_bsc__bts_alarm_history__zeoh_bts_alarm_history(logFileContent)
      case "flexi_bsc__system_configuration__zwoi_pr_file" =>
        parserFunctionReturn = flexi_bsc__system_configuration__zwoi_pr_file(logFileContent)
      case "flexi_bsc__sw_configuration__zwqo_run_bscpack" | "flexi_bsc__sw_configuration__fb_unit_info_zusi" =>
        parserFunctionReturn = flexi_bsc__sw_configuration__zwqo_run_bscpack(logFileContent)
      case "flexi_bsc__system_configuration__zwos_pr_file" =>
        parserFunctionReturn = flexi_bsc__system_configuration__zwos_pr_file(logFileContent)
      case "flexi_bsc__system_configuration__zwti_c" =>
        parserFunctionReturn = flexi_bsc__system_configuration__zwti_c(logFileContent)
      case "flexi_bsc__rnw_status_and_bsc_and_bcf_data__zego_bsc_timers" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data__zego_bsc_timers(logFileContent)
      case "flexi_bsc__bts_seg_and_trx_parameters__zeqo_basic1" =>
        parserFunctionReturn = flexi_bsc__bts_seg_and_trx_parameters__zeqo_basic1(logFileContent)
      case "flexi_bsc__io_system__zi2h_protocol_state" =>
        parserFunctionReturn = flexi_bsc__io_system__zi2h_protocol_state(logFileContent)
      case "flexi_bsc__cell_broadcast_status__zecp_cell_broadcast_msg" =>
        parserFunctionReturn = flexi_bsc__cell_broadcast_status__zecp_cell_broadcast_msg(logFileContent)
      case "flexi_bsc__utpfil_and_memory_files__fb_ipc_obsolete_utpfil" =>
        parserFunctionReturn = flexi_bsc__utpfil_and_memory_files__fb_ipc_obsolete_utpfil(logFileContent)
      case "flexi_bsc__bsc_alarm_history__zahp_bsc_alarm_histroy" =>
        parserFunctionReturn = flexi_bsc__bsc_alarm_history__zahp_bsc_alarm_histroy(logFileContent)
      case "flexi_bsc__bsc_alarm_history_txt__computer_logs" =>
        parserFunctionReturn = flexi_bsc__bsc_alarm_history_txt__computer_logs(logFileContent)
      case "flexi_bsc__rnw_status_and_bsc_and_bcf_data__zeek_fbpp_status" | "flexi_bsc__rnw_status_and_bsc_and_bcf_data_txt__zeek" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data__zeek_fbpp_status(logFileContent)
      case "flexi_bsc__measurement_status__zifi_event_sending_status" =>
        parserFunctionReturn = flexi_bsc__measurement_status__zifi_event_sending_status(logFileContent)
      case "flexi_bsc__finaletpaping__ip_ping_results" | "flexi_bsc__finaletpaping_txt__packet_loss" =>
        parserFunctionReturn = flexi_bsc__finaletpaping__ip_ping_results(logFileContent)
      case "flexi_bsc__trx_deletion_error__zerd" =>
        parserFunctionReturn = flexi_bsc__trx_deletion_error__zerd(logFileContent)
      case "flexi_bsc__bsc_alarm_history_txt__bsc_alarm" | "flexi_bsc__bsc_alarm_history__bsc_alarm" | "mcbsc__bsc_alarm_history__bsc_alarm" =>
        parserFunctionReturn = flexi_bsc__bsc_alarm_history_txt__bsc_alarm(logFileContent)
      case "flexi_bsc__rnw_status_and_bsc_and_bcf_data__zefo_c_m_plane_ip" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data__zefo_c_m_plane_ip(logFileContent)
      case "flexi_bsc__system_configuration__zwti_u_configuration" =>
        parserFunctionReturn = flexi_bsc__system_configuration__zwti_u_configuration(logFileContent)
      case "flexi_bsc__bsc_alarms__zaho_bsc_alarm_check" =>
        parserFunctionReturn = flexi_bsc__bsc_alarms__zaho_bsc_alarm_check(logFileContent)
      case "flexi_bsc__ip_configurations__zqri_bcsu_internal_ip" | "flexi_bsc__ip_configurations__fb_ipc_zqri_bcsu" =>
        parserFunctionReturn = flexi_bsc__ip_configurations__zqri_bcsu_internal_ip(logFileContent)
      case "mcrnc__rnchw__rnchw_smartctl_hdd_grown_defect" | "mcrnc__rnchw__hdd_grown_defect" =>
        parserFunctionReturn = mcrnc__rnchw__rnchw_smartctl_hdd_grown_defect(logFileContent)
      case "mcrnc__rncsignaling__rncsignaling_sccp_destination_point_code" =>
        parserFunctionReturn = mcrnc__rncsignaling__rncsignaling_sccp_destination_point_code(logFileContent)
      case "mcrnc__rncsignaling__rncsignaling_ss7_association" =>
        parserFunctionReturn = mcrnc__rncsignaling__rncsignaling_ss7_association(logFileContent)
      case "mcrnc__rncsignaling__rncsignalingsccpsubsystemremote" =>
        parserFunctionReturn = mcrnc__rncsignaling__rncsignalingsccpsubsystemremote(logFileContent)
      case "wcdma_rnc__omu_computer_logs__omu_computer_logs" =>
        parserFunctionReturn = wcdma_rnc__omu_computer_logs__omu_computer_logs(logFileContent)
      case "flexi_bsc__rnw_status_and_bsc_and_bcf_data__zeeo_bsc_dfca" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data__zeeo_bsc_dfca(logFileContent)
      case "flexi_mr_bts_lte__rawalarmhistory__mrbts_rawalarmhistory" =>
        parserFunctionReturn = flexi_mr_bts_lte__rawalarmhistory__mrbts_rawalarmhistory(logFileContent)
      case "flexi_bsc__computer_logs__zdde_computer_logs" =>
        parserFunctionReturn = flexi_bsc__computer_logs__zdde_computer_logs(logFileContent)
      case "flexi_bsc__ip_configurations__zqri_ip_configuration" =>
        parserFunctionReturn = flexi_bsc__ip_configurations__zqri_ip_configuration(logFileContent)
      case "flexi_mr_bts_lte__1011_rawalarmHistory__parse_rawalarmhistory" | "sran_bts__1011_rawalarmhistory__parse_rawalarmhistory" | "flexi_mr_bts_lte__1011_rawalarmhistory__1011_rawalarmhistory" | "sran_bts__1011_rawalarmhistory__rawalarmhistory" =>
        parserFunctionReturn = flexi_mr_bts_lte__1011_rawalarmhistory__parse_rawalarmhistory(logFileContent)
      case "mcrnc__rncrnw__radio_network_iuparams" =>
        parserFunctionReturn = mcrnc__rncrnw__radio_network_iuparams(logFileContent)
      case "mcrnc__rnchw__embedded_sw_status" | "mcrnc__rnchw__esw_status" =>
        parserFunctionReturn = mcrnc__rnchw__embedded_sw_status(logFileContent)
      case "mcrnc__rnchw__lmp_hw_status" =>
        parserFunctionReturn = mcrnc__rnchw__lmp_hw_status(logFileContent)
      case "mcrnc__rnchw__rnchwsfpstatus" =>
        parserFunctionReturn = mcrnc__rnchw__rnchwsfpstatus(logFileContent)
      case "flexi_bsc__oem_network__zqdi_max_osi_data" =>
        parserFunctionReturn = flexi_bsc__oem_network__zqdi_max_osi_data(logFileContent)
      case "flexi_bsc__io_system__zw7i_fea_state" | "flexi_bsc__io_system__zw7i_fea_states" =>
        parserFunctionReturn = flexi_bsc__io_system__zw7i_fea_state(logFileContent)
      case "flexi_bsc__swu__swu_monitor_esb24" =>
        parserFunctionReturn = flexi_bsc__swu__swu_monitor_esb24(logFileContent)
      case "flexi_bsc__ip_configurations__zqri_etpsig_m" | "flexi_bsc__ip_configurations__fb_ipc_etpsig_j" =>
        parserFunctionReturn = flexi_bsc__ip_configurations__zqri_etpsig_m(logFileContent)
      case "flexi_bsc__unit_information__zusi_unitinfo" =>
        parserFunctionReturn = flexi_bsc__unit_information__zusi_unitinfo(logFileContent)
      case "flexi_bsc__etp_logs__etp_active_call" =>
        parserFunctionReturn = flexi_bsc__etp_logs__etp_active_call(logFileContent)
      case "flexi_bsc__bts_alarms__zeol_bts_alarms" =>
        parserFunctionReturn = flexi_bsc__bts_alarms__zeol_bts_alarms(logFileContent)
      case "flexi_bsc__database_status__zdbs_dbstatecheck" =>
        parserFunctionReturn = flexi_bsc__database_status__zdbs_dbstatecheck(logFileContent)
      case "flexi_bsc__sw_configuration__zwqo_cr_omupack" =>
        parserFunctionReturn = flexi_bsc__sw_configuration__zwqo_cr_omupack(logFileContent)
      case "flexi_bsc__locked_files__ziwx_alhistgx" =>
        parserFunctionReturn = flexi_bsc__locked_files__ziwx_alhistgx(logFileContent)
      case "flexi_bsc__ip_configurations__fb-ipc-zqri-bcsu" =>
        parserFunctionReturn = flexi_bsc__ip_configurations__zqri_bcsu_internal_ip(logFileContent)
      case "flexi_bsc__io_system__zw7i_fea_usage" =>
        parserFunctionReturn = flexi_bsc__io_system__zw7i_fea_usage(logFileContent)
      case "flexi_bsc__switch_info__zw6g_topology" =>
        parserFunctionReturn = flexi_bsc__switch_info__zw6g_topology(logFileContent)
      case "flexi_bsc__boot_info_txt__zwdi" =>
        parserFunctionReturn = flexi_bsc__boot_info_txt__zwdi(logFileContent)
      case "flexi_bsc__rnw_status_and_bsc_and_bcf_data__zeeo_dinho" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data__zeeo_dinho(logFileContent)
      case "flexi_bsc__rnw_status_and_bsc_and_bcf_data_txt__fb_bsc_bcf_mc_sbnt" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data_txt__fb_bsc_bcf_mc_sbnt(logFileContent)
      case "flexi_bsc__clock_and_lapd_status__zdti_lapd_check" =>
        parserFunctionReturn = flexi_bsc__clock_and_lapd_status__zdti_lapd_check(logFileContent)
      case "flexi_bsc__clock_and_lapd_status__zdri_sync_input" =>
        parserFunctionReturn = flexi_bsc__clock_and_lapd_status__zdri_sync_input(logFileContent)
      case "flexi_bsc__ip_configurations__zqvi_pad_parameters" =>
        parserFunctionReturn = flexi_bsc__ip_configurations__zqvi_pad_parameters(logFileContent)
      case "flexi_bsc__ss7_network_txt__znci_m3ua_based_signalling_links" =>
        parserFunctionReturn = flexi_bsc__ss7_network_txt__znci_m3ua_based_signalling_links(logFileContent)
      case "flexi_bsc__supervision_and_disk_status__zdoi_omu_mcmu_bcsu_m_" =>
        parserFunctionReturn = flexi_bsc__supervision_and_disk_status__zdoi_omu_mcmu_bcsu_m_(logFileContent)
      case "flexi_bsc__bsc_alarm_history_txt__zahp_alarm_sup" | "flexi_bsc__bsc_alarm_history_txt__suntest" =>
        parserFunctionReturn = flexi_bsc__bsc_alarm_history_txt__zahp_alarm_sup(logFileContent)
      case "flexi_bsc__supplementary_ss7_network__zosk" =>
        parserFunctionReturn = flexibsc__supplementary_ss7_network__zosk(logFileContent)
      case "flexi_bsc__boot_info_txt__zwdi_boot_image_of_units" =>
        parserFunctionReturn = flexi_bsc__boot_info_txt__zwdi_boot_image_of_units(logFileContent)
      case "flexi_bsc__ip_configurations__zqkb_static_routes" =>
        parserFunctionReturn = flexi_bsc__ip_configurations__zqkb_static_routes(logFileContent)
      case "flexi_bsc__ip_configurations__zqkb_statroute" =>
        parserFunctionReturn = flexi_bsc__ip_configurations__zqkb_statroute(logFileContent)
      case "flexi_bsc__supervision_and_disk_status_txt__fb_unit_memory_check" =>
        parserFunctionReturn = flexi_bsc__supervision_and_disk_status_txt__fb_unit_memory_check(logFileContent)
      case "flexi_bsc__rnw_status_and_bsc_and_bcf_data__zeoe_bts_blocked_alarms" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data__zeoe_bts_blocked_alarms(logFileContent)
      case "flexi_bsc__unit_information__fb_mc_unit_status" =>
        parserFunctionReturn = flexi_bsc__unit_information__fb_mc_unit_status(logFileContent)
      case "flexi_bsc__bts_sw_lmu_and_abis_pool_data__zewo_bcf_swpack" =>
        parserFunctionReturn = flexi_bsc__bts_sm_lmu_and_abis_pool_data__zewo_bcf_swpack(logFileContent)
      case "flexi_bsc__swu_7__tsn_0911_swu_7_edgeport" | "flexi_bsc__swu_6_txt__edge_test" | "flexi_bsc__swu_6__tsn_0911_swu_6_edgeport" =>
        parserFunctionReturn = flexi_bsc__swu_7__tsn_0911_swu_7_edgeport(logFileContent)
      case "flexi_bsc__swu_7__tsn_0911_swu_6_edgeport" =>
        parserFunctionReturn = flexi_bsc__swu_7__tsn_0911_swu_7_edgeport(logFileContent)
      case "flexi_bsc__switch_info__switch_working_state" =>
        parserFunctionReturn = flexi_bsc__switch_info__switch_working_state(logFileContent)
      case "flexi_bsc__rnw_status_and_bsc_and_bcf_data__zefo_bcf_all_parameters1" | "flexi_bsc__rnw_status_and_bsc_and_bcf_data__zefo_bcf_all_parameters" | "flexi_bsc__rnw_status_and_bsc_and_bcf_data_txt__zefo_bcf_all_parameter" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data__zefo_bcf_all_parameters1(logFileContent)
      case "flexi_bsc__ss7_network__znci_signalling_link_data" =>
        parserFunctionReturn = flexi_bsc__ss7_network__znci_signalling_link_data(logFileContent)
      case "flexi_bsc__bts_seg_and_trx_parameters__zeqo_btsparameter" =>
        parserFunctionReturn = flexi_bsc__bts_seg_and_trx_parameters__zeqo_btsparameter(logFileContent)
      case "flexi_bsc__bts_sw_lmu_and_abis_pool_data_txt__zewl_output" =>
        parserFunctionReturn = flexi_bsc__bts_sw_lmu_and_abis_pool_data_txt__zewl_output(logFileContent)
      case "flexi_bsc__preprocessor_sw__zdpp_cls_preproinput" =>
        parserFunctionReturn = flexi_bsc__preprocessor_sw__zdpp_cls_preproinput(logFileContent)
      case "sran_bts__extendedsysteminfo__extendedsysteminfo_diskusage" | "sran_bts__extendedsysteminfo_log__extendedsysteminfo_diskusage" =>
        parserFunctionReturn = sran_bts__extendedsysteminfo__extendedsysteminfo_diskusage(logFileContent)
      case "flexi_bsc__etxx_configuration__zwti_pp_etphotlink" =>
        parserFunctionReturn = flexi_bsc__etxx_configuration__zwti_pp_etphotlink(logFileContent)
      case "flexi_bsc__etxx_configuration__zesl_pcu_pcuonetp" =>
        parserFunctionReturn = flexi_bsc__etxx_configuration__zesl_pcu_pcuonetp(logFileContent)
      case "flexi_bsc__supplementary_ss7_network__zoyo" =>
        parserFunctionReturn = flexi_bsc__supplementary_ss7_network__zoyo(logFileContent)
      case "flexi_bsc__supervision_and_disk_status__zdoi_omu_mcmu_bcsu_p_" =>
        parserFunctionReturn = flexi_bsc__supervision_and_disk_status__zdoi_omu_mcmu_bcsu_p_(logFileContent)
      case "sran_bts__scf__sbtstimezone" =>
        parserFunctionReturn = sran_bts__scf__sbtstimezone(logFileContent)
      case "sran_bts__scf__scf_pmax" =>
        parserFunctionReturn = sran_bts__scf__scf_pmax(logFileContent)
      case "sran_bts__dump_routing_table__routingtablenew" | "flexi_mr_bts_lte__dump_routing_table_txt__routingtablenew" =>
        parserFunctionReturn = sran_bts__dump_routing_table__routingtablenew(logFileContent)
      case "sran_bts__snapshot_file_list__snapshot_file_list_countofmodules" =>
        parserFunctionReturn = sran_bts__snapshot_file_list__snapshot_file_list_countofmodules(logFileContent)
      case "sran_bts__dump_routing_table__routingtable" | "sran_bts__dump_routing_table_txt__routingtable" =>
        parserFunctionReturn = sran_bts__dump_routing_table__routingtable(logFileContent)
      case "sran_bts__1011_rawalarmhistory__bts_1011_rawalarmhistory" =>
        parserFunctionReturn = sran_bts__1011_rawalarmhistory__bts_1011_rawalarmhistory(logFileContent)
      /*  case "flexi_bsc__ip_configurations__zqkb_static_routes" =>
          parserFunctionReturn = flexibsc__ip_configurations__zqkb_static_routes(logfilecontent)
       case "flexi_bsc__rnw_status_and_bsc_and_bcf_data__zeoe_bts_blocked_alarms" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data__zeoe_bts_blocked_alarms(logfilecontent)
      */
      case "flexi_bsc__bts_sm_lmu_and_abis_pool_data__zewo_bcf_swpack" =>
        parserFunctionReturn = flexi_bsc__bts_sm_lmu_and_abis_pool_data__zewo_bcf_swpack(logFileContent)

      case "flexi_bsc___ip_configurations" =>
        parserFunctionReturn = flexi_bsc___ip_configurations(logFileContent)
      case "flexi_bsc__ss7_network__zobl_ip_broadcast" =>
        parserFunctionReturn = flexi_bsc__ss7_network__zobl_ip_broadcast(logFileContent)
      case "flexi_bsc__ss7_network__zobi_sccpbroadcast_defination" =>
        parserFunctionReturn = flexi_bsc__ss7_network__zobi_sccpbroadcast_defination(logFileContent)
      case "mcrnc__rnchw__embedded_sw_version" | "mcrnc__rnchw__esw_version_check" =>
        parserFunctionReturn = mcrnc__rnchw__embedded_sw_version(logFileContent)
      case "sran_bts__scf__x2_link_status" =>
        parserFunctionReturn = sran_bts__scf__x2_link_status(logFileContent)
      case "sran_bts__snapshot_file_list__dsp_crash" =>
        parserFunctionReturn = sran_bts__snapshot_file_list__dsp_crash(logFileContent)
      case "sran_bts__011_rawalarmhistory__rawalarmhistory" =>
        parserFunctionReturn = sran_bts__011_rawalarmhistory__rawalarmhistory(logFileContent)
      case "sran_bts__scf__scf_dlmimotype" =>
        parserFunctionReturn = sran_bts__scf__scf_dlmimotype(logFileContent)

      case "sran_bts__runtime__rfmodulefaults" =>
        parserFunctionReturn = sran_bts__runtime__rfmodulefaults(logFileContent)
      case "mcrnc__rncalarm__mcrnc_active_alarm" | "mcrnc__rncalarm_txt__rnc_alarm" =>
        parserFunctionReturn = mcrnc__rncalarm__mcrnc_active_alarm(logFileContent)
      case "sran_bts__lrm_dump__lrm_dump" =>
        parserFunctionReturn = sran_bts__lrm_dump__lrm_dump(logFileContent)
      case "sran_bts__scf__scf_channelgrouping" =>
        parserFunctionReturn = sran_bts__scf__scf_channelgrouping(logFileContent)
      case "sran_bts__extendedsystem__cp_traffic_wcdma" =>
        parserFunctionReturn = sran_bts__extendedsystem__cp_traffic_wcdma(logFileContent)
      case "wcdma_rnc__functional_units__zusi_full" | "wcdma_rnc__functional_units__functional_units" =>
        parserFunctionReturn = wcdma_rnc__functional_units__zusi_full(logFileContent)
      case "wcdma_rnc__diagnostics__diagnostics_report_history_unit_diagnose_status" =>
        parserFunctionReturn = wcdma_rnc__diagnostics__diagnostics_report_history_unit_diagnose_status(logFileContent)
      case "flexi_mr_bts_lte__trs__parse_ethlk" =>
        parserFunctionReturn = flexi_mr_bts_lte__trs__parse_ethlk(logFileContent)
      case "wcdma_rnc__active_alarms__rnc_active_alarm" =>
        parserFunctionReturn = wcdma_rnc__active_alarms__rnc_active_alarm(logFileContent)
      case "flexi_mr_bts_lte__messages_2__read_messages_2" =>
        parserFunctionReturn = flexi_mr_bts_lte__messages_2__read_messages_2(logFileContent)
      case "flexi_mr_bts_lte__runtime_btsom_log__1011_runtime" =>
        parserFunctionReturn = flexi_mr_bts_lte__runtime_btsom_log__1011_runtime(logFileContent)
      case "flexi_mr_bts_lte__011_rawalarmhistory__011_rawalarmhistory_alldata" =>
        parserFunctionReturn = flexi_mr_bts_lte__011_rawalarmhistory__011_rawalarmhistory_alldata(logFileContent)
      case "sran_bts__tas_extended_startup__tas_extended_startup_lmpipcheck" =>
        parserFunctionReturn = sran_bts__tas_extended_startup__tas_extended_startup_lmpipcheck(logFileContent)
      case "mcbsc__mcbc___zw6t_flowcontrol" =>
        parserFunctionReturn = mcbsc__mcbc___zw6t_flowcontrol(logFileContent)
      case "lte_oms__df__df_out" =>
        parserFunctionReturn = lte_oms__df__df_out(logFileContent)
      case "flexi_bsc__ip__fb_ipc_zqri_etpxunit" =>
        parserFunctionReturn = flexi_bsc__ip__fb_ipc_zqri_etpxunit(logFileContent)
      case "sran_bts__scf__scf_parameters_all" =>
        parserFunctionReturn = sran_bts__scf__scf_parameters_all(logFileContent)
      case "flexi_mr_bts_lte__scf_xml__fetch_lnrel" =>
        parserFunctionReturn = flexi_mr_bts_lte__scf_xml__fetch_lnrel(logFileContent)
      case "sran_bts__startup_log__startup_rmod_check" | "flexi_mr_bts_lte__startup__startup_rmod_check" =>
        parserFunctionReturn = sran_bts__startup_log__startup_rmod_check(logFileContent)
      case "lte_oms__cat__ioms_mirroring_error" =>
        parserFunctionReturn = lte_oms__cat__ioms_mirroring_error(logFileContent)
      case "lte_oms__zstatus__zstatus_out_alarmprocessor_check" =>
        parserFunctionReturn = lte_oms__zstatus__zstatus_out_alarmprocessor_check(logFileContent)
      case "lte_oms__alarms__alarms_alarmprocessor_check" =>
        parserFunctionReturn = lte_oms__alarms__alarms_alarmprocessor_check(logFileContent)
      case "lte_oms__syslog__spontaneous_ioms_reboot" =>
        parserFunctionReturn = lte_oms__syslog__spontaneous_ioms_reboot(logFileContent)
      case "wcdma_rnc__alarm_history__rnc_alarm_history" =>
        parserFunctionReturn = wcdma_rnc__alarm_history__rnc_alarm_history(logFileContent)
      case "wcdma_rnc__dsp_mml_data__cells_configured_in_dsp_pool" =>
        parserFunctionReturn = wcdma_rnc__dsp_mml_data__cells_configured_in_dsp_pool(logFileContent)
      case "flexi_mr_bts_lte__cupl__parse_scf_xml" =>
        parserFunctionReturn = flexi_mr_bts_lte__cupl__parse_scf_xml(logFileContent)
      case "sran_bts__runtime__fsp_136a_runtime" | "flexi_mr_bts_lte__runtime__fsp_136a_runtime" | "flexi_mr_bts_lte__pm__pm" =>
        parserFunctionReturn = sran_bts__runtime__fsp_136a_runtime(logFileContent)
      case "flexi_mr_bts_lte__123d_rawalarmhistory__123d_rawalarmhistory" =>
        parserFunctionReturn = flexi_mr_bts_lte__123d_rawalarmhistory__123d_rawalarmhistory(logFileContent)
      case "wcdma_rnc__wbts_info__wbts_wcell_count" =>
        parserFunctionReturn = wcdma_rnc__wbts_info__wbts_wcell_count(logFileContent)
      case "mcrnc__sw_manage_install__sw_manage_install" =>
        parserFunctionReturn = mcrnc__sw_manage_install__sw_manage_install(logFileContent)
      case "mcrnc__fsip_switch_port__fsip_switch_port" =>
        parserFunctionReturn = mcrnc__fsip_switch_port__fsip_switch_port(logFileContent)
      case "mcrnc__startuplog___dram_info" =>
        parserFunctionReturn = mcrnc__startuplog___dram_info(logFileContent)
      case "mcrnc__syslog__master_syslog_unit_text_data" =>
        parserFunctionReturn = mcrnc__syslog__master_syslog_unit_text_data(logFileContent)
      case "flexi_mr_bts_lte__1011_blackbox__parse_blackbox" | "flexi_mr_bts_td_lte__1011_blackbox__enb_safeguard_restart" | "flexi_mr_bts_lte__flexi_mr_bts_lte_011_blackbox__011_blackbox" | "flexi_mr_bts_lte__1011_blackbox__011_blackbox" =>
        parserFunctionReturn = flexi_mr_bts_lte__1011_blackbox__parse_blackbox(logFileContent)
      case "flexi_mr_wcdma_bts__pm__any_module_pm" | "flexi_mr_wcdma_bts__pm__any_module_pm1" =>
        parserFunctionReturn = flexi_mr_wcdma_bts__pm__any_module_pm(logFileContent)
      case "flexi_mr_wcdma_bts__1011_rawalarmhistory__x011_rawalarmhistory" =>
        parserFunctionReturn = flexi_mr_wcdma_bts__1011_rawalarmhistory__x011_rawalarmhistory(logFileContent)
      case "flexi_bsc__adjacent_cell_data_check__zeat_adjaceny_check" =>
        parserFunctionReturn = flexi_bsc__adjacent_cell_data_check__zeat_adjaceny_check(logFileContent)
      case "flexi_bsc__system_configuration__zwti_p_configuration" =>
        parserFunctionReturn = flexi_bsc__system_configuration__zwti_p_configuration(logFileContent)
      case "flexi_mr_bts_lte__runtime_default__1011_runtime_default" =>
        parserFunctionReturn = flexi_mr_bts_lte__runtime_default__1011_runtime_default(logFileContent)
      case "sran_bts__runtime_btsom__x011_runtime_btsom" | "sran_bts__runtime_default__x011_runtime_default" | "sran_bts__runtime_trsw__x011_runtime_trsw" | "sran_bts__runtime_btsom_log__fortestingonly_btsom" =>
        parserFunctionReturn = sran_bts__runtime_btsom__x011_runtime_btsom(logFileContent)
      case "flexi_mr_wcdma_bts__alarms_xml__alarms_xml" =>
        parserFunctionReturn = flexi_mr_wcdma_bts__alarms_xml__alarms_xml(logFileContent)
      case "sran_bts__011_filelistinfo_log__filelistinfo" =>
        parserFunctionReturn = sran_bts__011_filelistinfo_log__filelistinfo(logFileContent)
      case "btsmed__imp_upgrade__imp_upgrade_check_rpm_info" =>
        parserFunctionReturn = btsmed__imp_upgrade__imp_upgrade_check_rpm_info(logFileContent)
      case "btsmed__imp__imp_check_extra_info_alarm_8524" =>
        parserFunctionReturn = btsmed__imp__imp_check_extra_info_alarm_8524(logFileContent)
      case "flexi_bsc____tsn_0911_swu_edgeport" | "bsc3i__swu__tsn_0911_swu_edgeport" =>
        parserFunctionReturn = flexi_bsc____tsn_0911_swu_edgeport(logFileContent)
      case "flexi_bsc__rnw_status_and_bsc_and_bcf_data_txt__zeeo" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data_txt__zeeo(logFileContent)
      case "fixed_network__final_11050a20_TSF__tsf_parsing_sample" =>
        parserFunctionReturn = fixed_network__final_11050a20_TSF__tsf_parsing_sample(logFileContent)
      case "wcdma_rnc__ip_configuration_txt__zqri_network_if_data" =>
        parserFunctionReturn = wcdma_rnc__ip_configuration_txt__zqri_network_if_data(logFileContent)
      case "flexi_mr_wcdma_bts__1011_rawalarmhistory_txt__active_alarms" =>
        parserFunctionReturn = flexi_mr_wcdma_bts__1011_rawalarmhistory_txt__active_alarms(logFileContent)
      case "mcrnc__rnc_backplane_txt__rnc_backplane" =>
        parserFunctionReturn = mcrnc__rnc_backplane_txt__rnc_backplane(logFileContent)
      case "flexi_bsc__bcsu_5_pcu2_e_12_logs__ssv_pcu_esw" =>
        parserFunctionReturn = flexi_bsc__bcsu_5_pcu2_e_12_logs__ssv_pcu_esw(logFileContent)
      case "flexi_bsc__bts_seg_and_trx_parameters__bts_dfr8k_mode" =>
        parserFunctionReturn = flexi_bsc__bts_seg_and_trx_parameters__bts_dfr8k_mode(logFileContent)
      case "mcbsc__io_system__zw7i_fea_state" =>
        parserFunctionReturn = mcbsc__io_system__zw7i_fea_state(logFileContent)
      case "wcdma_rnc__mxu_10_computer_logs_txt__mxu_computer_logs" =>
        parserFunctionReturn = wcdma_rnc__mxu_10_computer_logs_txt__mxu_computer_logs(logFileContent)
      case "flexi_mr_bts_lte__ram_fault_history__fault_2" | "flexi_mr_bts_lte__fault_history__mrbts_ram_fault_history" =>
        parserFunctionReturn = flexi_mr_bts_lte__ram_fault_history__fault_2(logFileContent)
      case "flexi_mr_bts_lte__rawalarmhistory__alarm_1" =>
        parserFunctionReturn = flexi_mr_bts_lte__rawalarmhistory__alarm_1(logFileContent)
      case "flexi_bsc__swu__mstp_configuration" | "flexi_bsc__swu__local_mstp_configuration" =>
        parserFunctionReturn = flexi_bsc__swu__mstp_configuration(logFileContent)
      case "sran_bts__1011_blackbox__1011_blackbox" =>
        parserFunctionReturn = sran_bts__1011_blackbox__1011_blackbox(logFileContent)
      case "flexi_bsc__ip_configurations__zqwl" =>
        parserFunctionReturn = flexi_bsc__ip_configurations__zqwl(logFileContent)
      case "flexi_bsc__system_configuration__zwti_pi_piulocation" =>
        parserFunctionReturn = flexi_bsc__system_configuration__zwti_pi_piulocation(logFileContent)
      case "flexi_mr_wcdma_bts__amr_and_hspa_call_ru40_traceId1_moc__html_parsing" =>
        parserFunctionReturn = flexi_mr_wcdma_bts__amr_and_hspa_call_ru40_traceId1_moc__html_parsing(logFileContent)
      case "flexi_bsc__switch_info_txt__zwyi" =>
        parserFunctionReturn = flexi_bsc__switch_info_txt__zwyi(logFileContent)
      case "flexi_bsc__switch_info_txt__sg_test_table_pattern" =>
        parserFunctionReturn = flexi_bsc__switch_info_txt__sg_test_table_pattern(logFileContent)
      case "flexi_bsc__rnw_status_and_bsc_and_bcf_data_txt__zefo_sran_mutecall" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data_txt__zefo_sran_mutecall(logFileContent)
      case "mcbsc__bts_seg_and_trx_parameters__zeqo_bts_ibho" =>
        parserFunctionReturn = mcbsc__bts_seg_and_trx_parameters__zeqo_bts_ibho(logFileContent)
      case "flexi_bsc__rnw_status_and_bsc_and_bcf_data_txt__fb_zefo_mutecall" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data_txt__fb_zefo_mutecall(logFileContent)
      case "flexi_bsc__rnw_status_and_bsc_and_bcf_data_txt__zeei_bcsu_usage" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data_txt__zeei_bcsu_usage(logFileContent)
      case "bsc3i__switch_info__zw6g_topology" =>
        parserFunctionReturn = bsc3i__switch_info__zw6g_topology(logFileContent)
      case "flexi_bsc__etxx_configuration__zdwq_abis_d_channel" =>
        parserFunctionReturn = flexi_bsc__etxx_configuration__zdwq_abis_d_channel(logFileContent)
      case "flexi_bsc__bts_seg_and_trx_parameters__bts_dfca_mode" =>
        parserFunctionReturn = flexi_bsc__bts_seg_and_trx_parameters__bts_dfca_mode(logFileContent)
      case "flexi_bsc__locked_files__ziwx_lfiles" =>
        parserFunctionReturn = flexi_bsc__locked_files__ziwx_lfiles(logFileContent)
      case "sran_bts__runtime_btsom__runtime_btsom_only_wrn" =>
        parserFunctionReturn = sran_bts__runtime_btsom__runtime_btsom_only_wrn(logFileContent)
      case "flexi_bsc__ip_configurations_txt__fb_ipc_mc_etme_eep" =>
        parserFunctionReturn = flexi_bsc__ip_configurations_txt__fb_ipc_mc_etme_eep(logFileContent)
      case "flexi_bsc__supplementary_ss7_network__zocj" =>
        parserFunctionReturn = flexi_bsc__supplementary_ss7_network__zocj(logFileContent)
      case "flexi_bsc__clock_and_lapd_status__zdsb_lapd_state" =>
        parserFunctionReturn = flexi_bsc__clock_and_lapd_status__zdsb_lapd_state(logFileContent)
      case "flexi_bsc__measurement_status__ztpi_meas_state" =>
        parserFunctionReturn = flexi_bsc__measurement_status__ztpi_meas_state(logFileContent)
      case "flexi_bsc__preprocessor_sw__zdpx_gsw_preproinput" =>
        parserFunctionReturn = flexi_bsc__preprocessor_sw__zdpx_gsw_preproinput(logFileContent)
      case "flexi_bsc__supplementary_ss7_network__zodi" =>
        parserFunctionReturn = flexi_bsc__supplementary_ss7_network__zodi(logFileContent)
      case "flexi_bsc__ip_configurations__zqht" =>
        parserFunctionReturn = flexi_bsc__ip_configurations__zqht(logFileContent)
      case "flexi_bsc__ip_configurations_txt__zqkb_statroute" =>
        parserFunctionReturn = flexi_bsc__ip_configurations_txt__zqkb_statroute(logFileContent)
      case "flexi_bsc__database_status__zdbd_omu" =>
        parserFunctionReturn = flexi_bsc__database_status__zdbd_omu(logFileContent)
      case "flexi_bsc__bts_sw_lmu_and_abis_pool_data_txt__zewo_output" =>
        parserFunctionReturn = flexi_bsc__bts_sw_lmu_and_abis_pool_data_txt__zewo_output(logFileContent)
      case "flexi_bsc__rnw_status_and_bsc_and_bcf_data__zeei_bcsu" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data__zeei_bcsu(logFileContent)
      case "flexi_bsc__bsc_alarm_history_txt__zahp_alarmwithsupplentary" =>
        parserFunctionReturn = flexi_bsc__bsc_alarm_history_txt__zahp_alarmwithsupplentary(logFileContent)
      case "flexi_bsc__rnw_status_and_bsc_and_bcf_data_txt__zefo" =>
        parserFunctionReturn = flexi_bsc__rnw_status_and_bsc_and_bcf_data_txt__zefo(logFileContent)
      case "flexi_bsc__ip_configurations__fb_ipc_internal_ip" =>
        parserFunctionReturn = flexi_bsc__ip_configurations__fb_ipc_internal_ip(logFileContent)
      case "flexi_bsc__zeei__zeei_et" =>
        parserFunctionReturn = flexi_bsc__zeei__zeei_et(logFileContent)
      case "flexi_bsc__bsc_alarms__zahp_zaho_bsc_alarms" =>
        parserFunctionReturn = flexi_bsc__bsc_alarms__zahp_zaho_bsc_alarms(logFileContent)
      case "flexi_bsc__bsc_alarm_history_txt__alarm_sup" =>
        parserFunctionReturn = flexi_bsc__bsc_alarm_history_txt__alarm_sup(logFileContent)
      case "mcbsc__bsc_alarms__zaho_bsc_alarm_check" =>
        parserFunctionReturn = mcbsc__bsc_alarms__zaho_bsc_alarm_check(logFileContent)
      case "bsc3i__bsc_alarm__zahp_zaho_bsc_alarms" =>
        parserFunctionReturn = bsc3i__bsc_alarm__zahp_zaho_bsc_alarms(logFileContent)
      case "flexi_bsc__bsc_alarm_history__data_science" =>
        parserFunctionReturn = flexi_bsc__bsc_alarm_history__data_science(logFileContent)
      case "fixed_network__alexx__error_record_alexx" =>
        parserFunctionReturn = fixed_network__alexx__error_record_alexx(logFileContent)
      case _ =>
        println("Parser implementation not found for " + logElement)
    }
    parserFunctionReturn
  }

}
